[package]
name = "nex-protocols-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
nex-rs = {git = "https://github.com/zaksabeast/nex-rs.git", rev = "27c7c19" }
no_std_io = { git = "https://github.com/zaksabeast/no_std_io.git", rev = "48e68fa" }
num_enum = { version = "0.5", default-features = false }
